# Lab 07-1 Learning rate, Evaluation

In [2]:
import tensorflow as tf
import numpy as np

# Training dataset : 학습

In [3]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Test dataset : 평가

In [4]:
# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

# Training and Test datasets

In [6]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                        feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_data}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 6.2944307 [[-3.308036   -0.987469    0.6762766 ]
 [-0.99266094  0.11734478  0.66372705]
 [-1.0510052  -1.0087837  -1.805248  ]]
1 3.2126982 [[-3.2831204  -0.9877947   0.6516865 ]
 [-0.83035064  0.12873639  0.49002516]
 [-0.88886094 -1.011535   -1.9646409 ]]
2 2.3928106 [[-3.2584631  -1.0173643   0.65659875]
 [-0.66868573 -0.01440069  0.47149733]
 [-0.7278522  -1.1629272  -1.9742575 ]]
3 1.5718213 [[-3.236048   -1.022501    0.63932025]
 [-0.5136354  -0.03380059  0.3358469 ]
 [-0.5779053  -1.1918644  -2.0952673 ]]
4 0.9217732 [[-3.2232184  -1.037966    0.6419558 ]
 [-0.39997044 -0.11574307  0.30412441]
 [-0.4789648  -1.2704766  -2.1155956 ]]
5 0.77973497 [[-3.2350874  -1.0281669   0.64402574]
 [-0.41542077 -0.06627847  0.27011016]
 [-0.5188735  -1.2109748  -2.1351886 ]]
6 0.7548896 [[-3.2359116  -1.0354838   0.6521668 ]
 [-0.37300396 -0.10547854  0.26689342]
 [-0.49629772 -1.2401073  -2.1286318 ]]
7 0.745328 [[-3.2466946  -1.0310155   0.65848136]
 [-0.3844342  -0.08235905  0.25520417]


# Big learning rate

In [7]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

# Learning_rate 확인 !!!
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                        feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_data}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 2.9933074 [[-0.66591734  0.2863649   3.006222  ]
 [-2.3266456   2.1101365   1.8276392 ]
 [-0.62888837  1.4849135  -0.11998391]]
1 12.356411 [[-0.2909174  -0.50408804  3.421675  ]
 [ 0.11085439 -1.496656    2.996932  ]
 [ 1.8086116  -2.0762558   1.0036854 ]]
2 20.371916 [[ 0.08399403  0.05841196  2.4842634 ]
 [ 2.5481746   1.128344   -2.0653887 ]
 [ 4.2456856   0.7362442  -4.245888  ]]
3 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
4 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
5 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
6 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
7 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
8 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
9 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
10 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
11 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
12 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
13 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
14 nan [[nan nan nan]
 [nan nan na

# Small learning rate

In [8]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

# Learning_rate 확인 !!!
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                        feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_data}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 9.595525 [[-0.7340798  -1.3045465  -1.9229374 ]
 [-0.3623043   0.63681865 -0.04062838]
 [-1.2074138   1.6697253  -1.1006919 ]]
1 9.595525 [[-0.7340798  -1.3045465  -1.9229374 ]
 [-0.3623043   0.63681865 -0.04062838]
 [-1.2074138   1.6697253  -1.1006919 ]]
2 9.595525 [[-0.7340798  -1.3045465  -1.9229374 ]
 [-0.3623043   0.63681865 -0.04062838]
 [-1.2074138   1.6697253  -1.1006919 ]]
3 9.595525 [[-0.7340798  -1.3045465  -1.9229374 ]
 [-0.3623043   0.63681865 -0.04062838]
 [-1.2074138   1.6697253  -1.1006919 ]]
4 9.595525 [[-0.7340798  -1.3045465  -1.9229374 ]
 [-0.3623043   0.63681865 -0.04062838]
 [-1.2074138   1.6697253  -1.1006919 ]]
5 9.595525 [[-0.7340798  -1.3045465  -1.9229374 ]
 [-0.3623043   0.63681865 -0.04062838]
 [-1.2074138   1.6697253  -1.1006919 ]]
6 9.595525 [[-0.7340798  -1.3045465  -1.9229374 ]
 [-0.3623043   0.63681865 -0.04062838]
 [-1.2074138   1.6697253  -1.1006919 ]]
7 9.595525 [[-0.7340798  -1.3045465  -1.9229374 ]
 [-0.3623043   0.63681865 -0.04062838]
 [-1.207

# Non-normalized inputs

In [9]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session() 
sess.run(tf.global_variables_initializer())
for step in range(2001):
   cost_val, hy_val, _ = sess.run(
      [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
   print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2978012500000.0 
Prediction:
 [[-1216293.1]
 [-2449903.8]
 [-1926969.5]
 [-1350400.6]
 [-1591753.4]
 [-1605163. ]
 [-1471087.8]
 [-1873350.5]]
1 Cost:  3.2718845e+27 
Prediction:
 [[4.0348768e+13]
 [8.1226203e+13]
 [6.3897726e+13]
 [4.4791966e+13]
 [5.2789728e+13]
 [5.3234048e+13]
 [4.8790845e+13]
 [6.2120448e+13]]
2 Cost:  inf 
Prediction:
 [[-1.3374144e+21]
 [-2.6923523e+21]
 [-2.1179765e+21]
 [-1.4846903e+21]
 [-1.7497868e+21]
 [-1.7645144e+21]
 [-1.6172385e+21]
 [-2.0590662e+21]]
3 Cost:  inf 
Prediction:
 [[4.4330408e+28]
 [8.9241657e+28]
 [7.0203191e+28]
 [4.9212064e+28]
 [5.7999047e+28]
 [5.8487213e+28]
 [5.3605551e+28]
 [6.8250526e+28]]
4 Cost:  inf 
Prediction:
 [[-1.4693912e+36]
 [-2.9580351e+36]
 [-2.3269795e+36]
 [-1.6312003e+36]
 [-1.9224566e+36]
 [-1.9386376e+36]
 [-1.7768285e+36]
 [-2.2622558e+36]]
5 Cost:  inf 
Prediction:
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]

# Non-normalized inputs (min-max scale)

In [2]:
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import MinMaxScaler

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = MinMaxScaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session() 
sess.run(tf.global_variables_initializer())
for step in range(2001):
   cost_val, hy_val, _ = sess.run(
      [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
   print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



MinMaxScaler(feature_range=array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02,
        8.31659973e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02,
        8.28070007e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02,
        8.24159973e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02,
        8.19239990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02,
        8.18979980e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02,
        8.20450012e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02,
        8.13669983e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02,
        8.09559998e+02]]))
Traceback (most recent call last):
  File "/Users/mindongjun/opt/anaconda3/envs/test2/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self