# Check TF version

In [1]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
tf.config.list_physical_devices()

Num GPUs Available:  1


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.9.2'

# Hello TensorFlow!

> 텐서플로우 1.0에서 2.0으로 넘어오면서 "session"과 "placeholder"가 사라졌다.  
> 참고 : https://eclipse360.tistory.com/40

In [4]:
hello = tf.constant("Hello, TensorFlow!")

tf.print(hello)

Metal device set to: Hello, TensorFlow!
Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-08-26 16:26:02.756902: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-08-26 16:26:02.757003: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


# Computational Graph

In [5]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)        # also tf.float32 implicitly

node3 = tf.add(node1, node2)
# node3 = node1 + node2

In [6]:
print("node1:", node1, "\n", "node2:", node2)
print("node3: ", node3)

node1: tf.Tensor(3.0, shape=(), dtype=float32) 
 node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3:  tf.Tensor(7.0, shape=(), dtype=float32)


<img width="155" alt="스크린샷 2022-07-26 오후 8 11 34" src="https://user-images.githubusercontent.com/91893721/180993362-d421224d-33b4-419f-8e1b-9fc15d333d48.png">

# "sess.run()" -> "tf.print()"


> "sess.run()" 을 이용해서 출력하는 방법 대신 "tf.print()" 을 이용한다.

In [7]:
# 1. tensorflow 안에 있는 print 함수 이용
tf.print("[node1, node2] : ", [node1, node2])
tf.print("node3 : ", node3)

# 2. python 안에 있는 print 함수 이용
print("[node1, node2] : ", [node1, node2])
print("node3 : ", node3)

# 3. 차이점 : 대괄호의 유무
tf.print(node1, node2)
tf.print([node1, node2])
print(node1, node2)
print([node1, node2])

[node1, node2] :  [3, 4]
node3 :  7
[node1, node2] :  [<tf.Tensor: shape=(), dtype=float32, numpy=3.0>, <tf.Tensor: shape=(), dtype=float32, numpy=4.0>]
node3 :  tf.Tensor(7.0, shape=(), dtype=float32)
3 4
[3, 4]
tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(4.0, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=3.0>, <tf.Tensor: shape=(), dtype=float32, numpy=4.0>]


# "tf.placeholder()" -> 함수 정의

> "tf.placeholder()" 을 이용하지 않고 함수를 새롭게 정의한다.

In [8]:
@tf.function
def adder(a, b):
    return a + b

A = tf.constant(1)
B = tf.constant(2)
print(adder(A, B))

C = tf.constant([1, 2])
D = tf.constant([3, 4])
print(adder(C, D))

E = tf.constant([[1, 2, 3], [4, 5, 6]])
F = tf.constant([[2, 3, 4], [5, 6, 7]])
print(adder(E, F))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 3  5  7]
 [ 9 11 13]], shape=(2, 3), dtype=int32)


2022-08-26 16:26:03.211331: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-08-26 16:26:03.211503: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-08-26 16:26:03.221092: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-08-26 16:26:03.227705: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [9]:
def add_and_triple(a, b):
    return 3 * adder(a, b)

tf.print(add_and_triple(3, 4.5))

22.5


# Tensors

<img width="828" alt="스크린샷 2022-07-18 오후 10 20 39" src="https://user-images.githubusercontent.com/91893721/179524501-9291e268-5a04-42da-8093-1eadaf5c0efb.png">
<img width="872" alt="스크린샷 2022-07-18 오후 10 20 50" src="https://user-images.githubusercontent.com/91893721/179524584-a7f19d50-ecb6-4ce9-9338-87af5c526bd9.png">
<img width="822" alt="스크린샷 2022-07-18 오후 10 28 09" src="https://user-images.githubusercontent.com/91893721/179525492-6e6f00f9-be9e-4c4f-8db1-ae61d382b32c.png">

In [10]:
3 # a rank 0 tensor; this is a scalar with shape []
[1. ,2., 3.] # a rank 1 tensor; this is a vector with shape [3]
[[1., 2., 3.], [4., 5., 6.]] # a rank 2 tensor; a matrix with shape [2, 3]
[[[1., 2., 3.]], [[7., 8., 9.]]] # a rank 3 tensor with shape [2, 1, 3]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]